### ISSUE TITLE
How to use the pretrained models?

### ISSUE THREAD

**Issue by 2401ch** [elvisyjlin/AttGAN-PyTorch#1]
I download the pretrained models,but there is no setting.txt. I use the txt thar is created by train.py. However, i can not test by the pretrained models,  "Error(s) in loading state_dict for Generator:
        Unexpected key(s) in state_dict......" How the setting the network about pretrained???

**Comment by elvisyjlin** [comment]
Hi @chenghan1995 , 
I'm sorry that I didn't put the `setting.txt` in both pertained model files. The new zip files have been uploaded. Please download them again. Let me know if you have any other questions.

**Comment by 2401ch** [comment]
Thank you for your valuable work.
