### ISSUE TITLE
Could the attribute style be manipulated in this projects?

### ISSUE THREAD

**Issue by 2401ch** [elvisyjlin/AttGAN-PyTorch#2]
It is mentioned in the paper that AttGAN could manipulate the attribute style. However, I did not find the relevant code in this project. Does the project hace the function or not?

**Comment by elvisyjlin** [comment]
I'm sorry, but neither this project nor the author's repository does the attribute style manipulation.

In the paper, attribute style manipulation is mentioned as a extended version of AttGAN. By maximizing mutual information between style controllers and generated images, you can make AttGAN learn the fine-grained controll of each attribute in an unsupervised manner. It is similar to infoGAN and CFGAN.

Currently, I have no plan to do it. If you'd like to implement it, this infoGAN (https://github.com/pianomania/infoGAN-pytorch) is a good example to start.

**Comment by 2401ch** [comment]
Thanks a lot for your sincere answer.
