### ISSUE TITLE
did you not use any initialization for Conv layer weight？

### ISSUE THREAD

**Issue by Johnson-yue** [elvisyjlin/AttGAN-PyTorch#20]
Hi， I check twice for your code 。 did you not use any initialization function for model weight ??

**Comment by elvisyjlin** [comment]
No, I do not use any fancy initialization function for all layers in AttGAN. I thought I tried two or three weight initializations and found that there was no much difference. If you want to know the exact initialization method for each layer, please check out the PyTorch documentation page (https://pytorch.org/docs/0.4.0/nn.html) and click the source of that layer.

For example, the convolutional layers is here: https://pytorch.org/docs/0.4.0/_modules/torch/nn/modules/conv.html#Conv1d
The weight initialization is defined in `reset_parameters()`.

**Comment by Johnson-yue** [comment]
ok， this is good result ！！ thank you
