### ISSUE TITLE
One problem in attgan.py

### ISSUE THREAD

**Issue by liang23333** [elvisyjlin/AttGAN-PyTorch#22]
Hi, if i want to change the original attributes to other 14 attributes , in attgan.py i need to modify the self.fc_cls of discriminators, do i need to make any other changes?

**Comment by elvisyjlin** [comment]
Hi @liang23333, you found the code that I didn't write perfectly. To train the model on other attributes, you need to:
1. Put your target attributes in `attrs_default` of [train.py](https://github.com/elvisyjlin/AttGAN-PyTorch/blob/master/train.py).
2. Set the output dimension of `self.fc_cls` [here](https://github.com/elvisyjlin/AttGAN-PyTorch/blob/master/attgan.py#L106) to the number of your target attributes. Please overwrite the default value 13 there.

I will fix it in the near future. Thank you!
