### ISSUE TITLE
How to test on CelebA-HQ 256x256?

### ISSUE THREAD

**Issue by thinkerthinker** [elvisyjlin/AttGAN-PyTorch#3]
I find test.py is not suit for CelebA-HQ 256x256, how can i do it?

**Comment by elvisyjlin** [comment]
Hi @thinkerthinker , 

The code was initially written for only CelebA and I forgot to migrate the testing scripts with CelebA-HQ. I've pushed a new version, which should work for you. Please pull the repo again.

By the way, I found that the data path, attribute path, and image list path were not correct in the previous uploaded pretrained models. I've updated them in the Google Drive. You can revise them in `setting.txt`, or download the zip files again.

Thank you for pointing out this problem! Let me know if you still have problems with testing.

**Comment by thinkerthinker** [comment]
Thanks a lot! I will try it.
