### ISSUE TITLE
Epochs = 200, about 50 hours of training. Can I set epoch down a little? I'd like to ask, please. It's a good job.

### ISSUE THREAD

**Issue by zhangqian001** [elvisyjlin/AttGAN-PyTorch#30]
您能看懂中文吗？我用的3060单卡训练，epochs＝200，大概要训练50小时。想问问我可以把epoch设置小一点么，比如50，这样对模型的性能影响大吗？谢谢您了。

**Comment by elvisyjlin** [comment]
因為是兩年前的project，不記得少一點epoch的話效果如何。建議可以維持 `epochs=200`，訓練參數中的 `save_interval` 表示每間隔多少iteration存一次model，即使訓練到一半，也有model可以用。而 `sample_interval` 表示每間隔多少iteration產生一組sample images，可以由這些sample images檢視model學習的狀況。如果訓練在較小的圖像，如128x128，可以設置較大的batch，如此一來所需epoch比較少。而訓練在較大的圖像則需要較多epoch的時間。

**Comment by zhangqian001** [comment]
> 因為是兩年前的project，不記得少一點epoch的話效果如何。建議可以維持 `epochs=200`，訓練參數中的 `save_interval` 表示每間隔多少iteration存一次model，即使訓練到一半，也有model可以用。而 `sample_interval` 表示每間隔多少iteration產生一組sample images，可以由這些sample images檢視model學習的狀況。如果訓練在較小的圖像，如128x128，可以設置較大的batch，如此一來所需epoch比較少。而訓練在較大的圖像則需要較多epoch的時間。

明白了，太感谢您了。我训练的是celebA128x128的。目前是按照您的设置训练的，epochs也是200。另外问下，您还在做图像翻译方面的研究吗？我现在是入门不算很久的硕士生。
真的非常感谢您的回复，祝您身体健康，工作顺利。

**Comment by elvisyjlin** [comment]
不會，希望你能跑出好的結果。我在碩士班時期接觸比較多圖像翻譯，但是後來好一陣子沒碰了，現在做自然語言相關的工作。如果還有遇到什麼問題儘管問 (雖然不一定幫得上忙

**Comment by zhangqian001** [comment]
> 不會，希望你能跑出好的結果。我在碩士班時期接觸比較多圖像翻譯，但是後來好一陣子沒碰了，現在做自然語言相關的工作。如果還有遇到什麼問題儘管問 (雖然不一定幫得上忙

太感谢您了，真的非常感谢您的帮助。我目前是选择图像翻译做个过渡，准备发几篇论文去好的大学读博。如果学术上遇到问题了，能咨询您真的太好了。目前研究都是我自己一个人在搞的，所以即使遇到问题，也很难和学校的其他人交流。如果能够得到您的指点，那真的是太好了。再次感谢您的帮助，以后我有问题可以用github和您联系吗？多有打扰，敬请谅解。
祝您身体健康，快乐每一天！

**Comment by elvisyjlin** [comment]
可以，也可以用mail聯繫我，祝您研究順利！

**Comment by zhangqian001** [comment]
> 可以，也可以用mail聯繫我，祝您研究順利！

好的，谢谢您，祝您工作顺利。
