### ISSUE TITLE
Link for CelebA dataset does not work

### ISSUE THREAD

**Issue by alessiochisari** [elvisyjlin/AttGAN-PyTorch#32]
Can you please reload the link? This one is not working anymore.

**Comment by elvisyjlin** [comment]
The dataset link is moved to [Google Drive](https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8?resourcekey=0-5BR16BdXnb8hVj6CNHKzLg). Please download `Anno/list_attr_celeba.txt` and `Img/img_align_celeba.zip` from the link. Thanks for letting me know.
